baseURL = "https://dave.marquard.org"
title = "Dave Marquard"
theme = "gokarna"
languageCode = "en"
defaultContentLanguage = "en"
enableEmoji = true
enableRobotsTXT = true

# Choose one of emacs, trac or perldoc
pygmentsStyle = "monokai"

[params]
  description = "I build software. I live in New York. I travel, I dive, I run."
  avatarURL = "/images/avatar.jpg"
  avatarSize = "size-m"
  customHeadHTML = """<style>.header, .footer { display:none }</style>
  """
  socialIcons = [
    {name = "linkedin", url = "https://www.linkedin.com/in/davemarquard"},
    {name = "github", url = "https://github.com/dave-atx"},
    {name = "twitter", url = "https://twitter.com/lurp"},
    {name = "instagram", url = "https://www.instagram.com/dave_marquard/"},
    {name = "gmail", url = "mailto:dave@marquard.org"},
  ]
